DROP TABLE IF EXISTS USERS;

CREATE TABLE users
(
    id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name   VARCHAR NOT NULL,
    last_name    VARCHAR NOT NULL,
    phone_number VARCHAR NOT NULL,
    email        VARCHAR NOT NULL
);
CREATE UNIQUE INDEX users_unique_email_idx ON users (email);