#  https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
  jpa:
    generate-ddl: true
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        #        id.new_generator_mappings: false
        jdbc:
          lob:
            non_contextual_creation: true
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/static/templates/
    suffix: .html

  datasource:
    # ImMemory
    #    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:userapp}
    #    h2.console.enabled: true

    initialization-mode: always
    platform: postgres
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost/userapp}
    username: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    schema: classpath:/db/shema.sql
    data: classpath:/db/data.sql

logging:
  level:
    root: WARN
    edu.volkov.userapp: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} %highlight(%-5level) %cyan(%class{50}.%M:%L) - %green(%msg%n)"
