#  https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        id.new_generator_mappings: false

  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/static/templates/
    suffix: .html

  datasource:
    # ImMemory
    url: jdbc:h2:mem:userapp
    # tcp: jdbc:h2:tcp://localhost:9092/mem:userapp
    username: sa
    password:
  h2.console.enabled: true

logging:
  level:
    root: WARN
    edu.volkov.userapp: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} %highlight(%-5level) %cyan(%class{50}.%M:%L) - %green(%msg%n)"
